name: Build

on: [ push ]

jobs:
  build-test:
    name: Build & Test
    uses: ./.github/workflows/build-workflow.yml
    with:
      job_count: 3
      build_type: Release
      retention: 30
      upload_artifacts: true

  publish-test:
    name: Publish test results
    needs: build-test
    runs-on: [ self-hosted, docker ]
    steps:
      - uses: actions/download-artifact@v3
        name: Download test results
        with:
          name: ${{needs.build-test.outputs.test_artifact}}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            build/test-output/*.xml
  

  build-properitary:
    name: Build & Test (Proprietary licenses)
    needs: [ build-test ]
    uses: ./.github/workflows/build-workflow.yml
    with:
      job_count: 3
      build_type: Release
      retention: 30
      upload_artifacts: false
      is_proprietary: true
    secrets:
      gurobi_license: ${{ secrets.GUROBI_LICENSE_FILE }}
      gams_license: ${{ secrets.GAMS_LICENSE_FILE }}

