name: Build

# Build this on push
on: [ push ]

# Only build one build at a time
concurrency: push-build

jobs:
  # First, we build and test using the default build options and only open source external libraries
  build-test:
    name: Build & Test
    uses: ./.github/workflows/build-workflow.yml
    with:
      job_count: 4
      build_type: Release
      retention: 30
      upload_artifacts: true

  # Then, we build and test using all licenses included proprietary ones
  build-proprietary:
    name: Build & Test (Proprietary licenses)
    needs: [ build-test ]
    uses: ./.github/workflows/build-workflow.yml
    with:
      job_count: 4
      build_type: Release
      retention: 30
      upload_artifacts: false
      is_proprietary: true
      artifact_suffix: '-proprietary'
      build_args: '-DHAS_GAMS=on -DHAS_CPLEX=off -DHAS_GUROBI=on -DCOMPILE_TESTS=on -DSPDLOG_STATIC=on'
    secrets:
      gurobi_license: ${{ secrets.GUROBI_LICENSE_FILE }}
      gams_license: ${{ secrets.GAMS_LICENSE_FILE }}


  # Publish the test results as an output
  publish-test:
    name: Publish test results
    needs: [ build-test, build-proprietary ]
    runs-on: [ self-hosted, docker ]
    steps:
      - uses: actions/download-artifact@v3
        name: Download artifacts
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            artifacts/build/test-output/*.xml

