name: Build

on: [push]

jobs:
  build-test:
    uses: ./.github/workflows/build-workflow.yml
    with:
      job_count: 3
      build_type: Release
      retention: 30

  publish-test:
    needs: build-test
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/download-artifact@v3
        name: Download test results
        with:
          name: ${needs.build-test.outputs.test_artifact}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-output/*.xml


